# -*- coding: utf-8 -*-
"""L3-1(Strides-padding->CNN).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OyxECQzEj9qyI0HK5OrKVRCak6UlQKNe

# 🧠 CNN Hyperparameter Study — Padding, Stride & Pooling
### MNIST · TensorFlow/Keras · 6-Configuration Experiment

---

## 📋 Overview
This notebook systematically benchmarks **6 CNN configurations** on MNIST to measure
how **padding**, **stride**, and **max-pooling** affect:
- 🎯 Test & validation accuracy
- ⚡ Training speed (time per epoch)
- 📐 Feature map spatial dimensions
- 🔢 Total trainable parameters

Each model shares the same backbone (Conv2D → Flatten → Dense) so results are directly comparable.

---

## 🏗️ Pipeline

| Step | Description |
|------|-------------|
| **1. Reproducibility** | Seeds `tensorflow` and `numpy` with `SEED = 42` for consistent results |
| **2. Load Data** | Downloads MNIST → reshapes to `[N, 28, 28, 1]` → normalises to `[0, 1]` → one-hot encodes labels |
| **3. Safe Names** | Strips illegal characters from config names so they work as Keras layer names |
| **4. Configs** | Defines 6 experiment variants (see table below) |
| **5. Train Loop** | Builds, compiles, and trains each model for **5 epochs** · batch size **256** · 10% validation split |
| **6. Summary Table** | Collects metrics into a `pandas` DataFrame and prints a comparison table |
| **7. Bar Charts** | Plots Test Accuracy · Training Speed · Parameter Count side-by-side |
| **8. Feature Maps** | Visualises the first 4 conv feature maps per config to show spatial impact |

---

## 🔬 Experiment Configurations

| # | Config Name | Padding | Stride | Pooling |
|---|-------------|---------|--------|---------|
| 1 | Valid \| S1 \| Pool   | `valid` | 1 | ✅ MaxPool 2×2 |
| 2 | Same  \| S1 \| Pool   | `same`  | 1 | ✅ MaxPool 2×2 |
| 3 | Valid \| S2 \| Pool   | `valid` | 2 | ✅ MaxPool 2×2 |
| 4 | Same  \| S2 \| Pool   | `same`  | 2 | ✅ MaxPool 2×2 |
| 5 | Same  \| S1 \| NoPool | `same`  | 1 | ❌ No pooling  |
| 6 | Same  \| S2 \| NoPool | `same`  | 2 | ❌ No pooling  |

> 💡 Configs 5 & 6 isolate the effect of **stride alone** (no pooling) for a clean comparison.

---

## ⚙️ Shared Architecture (per config)
```
Input (28×28×1)
    └── Conv2D(32 filters, 3×3, ReLU)   ← padding & stride vary
           └── [MaxPool2D(2×2)]          ← optional
                  └── Flatten
                         └── Dense(10, Softmax)
```

---

## 📊 Metrics Collected

| Column | Description |
|--------|-------------|
| `FeatureMap` | Spatial size of conv output (e.g. `26×26` or `28×28`) |
| `Params` | Total trainable parameters |
| `Time/Epoch(s)` | Average wall-clock time per training epoch |
| `ValAcc` | Validation accuracy at final epoch |
| `TestAcc` | Accuracy on held-out MNIST test set (10 000 samples) |

---

## 📈 Visualisations Produced

1. **Test Accuracy vs Config** — which settings generalise best
2. **Training Speed vs Config** — compute cost of each variant
3. **Parameter Count vs Config** — model size comparison
4. **Feature Map Grid** — `6 configs × 5 columns` showing raw input + 4 learned filters per config

---

## 📦 Dependencies
```python
tensorflow  numpy  matplotlib  pandas
```

> Install in Colab: `!pip install tensorflow numpy matplotlib pandas`

---

## 🔑 Key Concepts

| Term | Meaning |
|------|---------|
| **`padding="valid"`** | No padding — output shrinks by `(kernel-1)` per side |
| **`padding="same"`** | Zero-pads input so output matches input spatial size (at stride 1) |
| **`strides=2`** | Skips every other position — halves feature map size, speeds up training |
| **`MaxPooling2D`** | Takes the maximum in each 2×2 window — further halves spatial dims |

---
"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import time
import re

# ============================================================
# 1. Reproducibility
# ============================================================
SEED = 42
tf.random.set_seed(SEED)
np.random.seed(SEED)

# ============================================================
# 2. Load Data (MNIST)
# ============================================================
print("Downloading MNIST dataset...")
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

x_train = x_train.reshape(-1, 28, 28, 1).astype("float32") / 255.0
x_test  = x_test.reshape(-1, 28, 28, 1).astype("float32") / 255.0

y_train = keras.utils.to_categorical(y_train, 10)
y_test  = keras.utils.to_categorical(y_test, 10)

sample_digit = x_test[0:1]

# ============================================================
# 3. Utility: safe TF names
# ============================================================
def safe(name):
    return re.sub(r'[^A-Za-z0-9_.\\/>-]', '_', name)

# ============================================================
# 4. Experiment Configurations
# ============================================================
configs = [
    {"padding":"valid","stride":1,"pool":True,  "name":"Valid | S1 | Pool"},
    {"padding":"same","stride":1,"pool":True,   "name":"Same  | S1 | Pool"},
    {"padding":"valid","stride":2,"pool":True,  "name":"Valid | S2 | Pool"},
    {"padding":"same","stride":2,"pool":True,   "name":"Same  | S2 | Pool"},

    # isolate stride (no pooling)
    {"padding":"same","stride":1,"pool":False,"name":"Same  | S1 | NoPool"},
    {"padding":"same","stride":2,"pool":False,"name":"Same  | S2 | NoPool"},
]

results = []
feature_maps_to_plot = []

print("\nStarting Experiments...")

# ============================================================
# 5. Run Experiments
# ============================================================
for cfg in configs:

    cfg_name = safe(cfg["name"])

    # ---- Build model ----
    inputs = layers.Input(shape=(28,28,1), name=f"{cfg_name}_input")

    conv = layers.Conv2D(
        32, (3,3),
        padding=cfg["padding"],
        strides=cfg["stride"],
        activation="relu",
        name=f"{cfg_name}_conv"
    )(inputs)

    feature_shape = conv.shape[1:3]

    x = conv
    if cfg["pool"]:
        x = layers.MaxPooling2D((2,2), name=f"{cfg_name}_pool")(x)

    x = layers.Flatten(name=f"{cfg_name}_flat")(x)
    outputs = layers.Dense(10, activation="softmax", name=f"{cfg_name}_out")(x)

    model = keras.Model(inputs, outputs, name=cfg_name)

    # ---- Params ----
    params = model.count_params()

    # ---- Feature maps ----
    fmap_model = keras.Model(inputs, conv)
    maps = fmap_model.predict(sample_digit, verbose=0)

    # ---- Train ----
    model.compile(optimizer="adam",
                  loss="categorical_crossentropy",
                  metrics=["accuracy"])

    epochs = 5
    start = time.time()

    history = model.fit(
        x_train, y_train,
        epochs=epochs,
        batch_size=256,
        verbose=0,
        validation_split=0.1
    )

    total_time = time.time() - start
    time_per_epoch = total_time / epochs

    _, acc = model.evaluate(x_test, y_test, verbose=0)

    results.append({
        "Config": cfg["name"],
        "Padding": cfg["padding"],
        "Stride": cfg["stride"],
        "Pool": cfg["pool"],
        "FeatureMap": f"{feature_shape[0]}x{feature_shape[1]}",
        "Params": params,
        "Time/Epoch(s)": round(time_per_epoch,3),
        "ValAcc": round(history.history["val_accuracy"][-1],4),
        "TestAcc": round(acc,4)
    })

    feature_maps_to_plot.append((maps, cfg["name"]))

# ============================================================
# 6. Summary Table
# ============================================================
df = pd.DataFrame(results)

print("\n" + "="*70)
print("EXPERIMENT SUMMARY")
print("="*70)
print(df.to_string(index=False))

# ============================================================
# 7. Quantitative Plots
# ============================================================
plt.figure()
plt.bar(df["Config"], df["TestAcc"])
plt.xticks(rotation=45)
plt.title("Test Accuracy vs Config")
plt.show()

plt.figure()
plt.bar(df["Config"], df["Time/Epoch(s)"])
plt.xticks(rotation=45)
plt.title("Training Speed vs Config")
plt.show()

plt.figure()
plt.bar(df["Config"], df["Params"])
plt.xticks(rotation=45)
plt.title("Parameter Count vs Config")
plt.show()

# ============================================================
# 8. Feature Map Visualization
# ============================================================
rows = len(feature_maps_to_plot)
cols = 5

fig, axes = plt.subplots(rows, cols, figsize=(16, 3*rows))
plt.subplots_adjust(hspace=0.5)

for i, (maps, name) in enumerate(feature_maps_to_plot):

    axes[i,0].imshow(sample_digit[0,:,:,0], cmap="gray")
    axes[i,0].set_title(f"{name}\nInput")
    axes[i,0].axis("off")

    for j in range(1, cols):
        axes[i,j].imshow(maps[0,:,:,j], cmap="viridis")
        axes[i,j].set_title(f"F{j}")
        axes[i,j].axis("off")

plt.suptitle("Padding & Stride Impact on Feature Maps", fontsize=16)
plt.show()